# Generated by Django 5.2.5 on 2025-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'customer'), ('seller', 'seller')], default='customer', max_length=10),
        ),
    ]
