# Generated by Django 5.2.5 on 2025-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards_of_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='Karta raqami')),
                ('expire_date', models.DateField(verbose_name='Amal qilish muddati')),
            ],
        ),
    ]
