# Generated by Django 5.2.5 on 2025-08-10 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name="Do'kon nomi")),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_images/', verbose_name="Do'kon rasmi")),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$', 'Telefon raqami +998 bilan boshlanishi kerak')], verbose_name='Telefon raqami')),
                ('location', models.BigIntegerField(blank=True, null=True, verbose_name='Joylashuv ID')),
            ],
            options={
                'verbose_name': "Do'kon",
                'verbose_name_plural': "Do'konlar",
                'ordering': ['name'],
            },
        ),
    ]
